### ISSUE TITLE
Socket issue after migrating aks cluster to 1.19 version which has containerd as runtime

### ISSUE THREAD

**Issue by krupakar-code** [ganrad/Az-DevOps-Agent-On-AKS#7]
Once the cluster is migrated to 1.19 version which has containerd as the default runtime, the yaml deployment fails as it has volume mounts to /var/run/docker.sock(which will not be present in containerd runtime). Kindly help on the same on how to mount to /var/run/containerd/containerd.sock

**Comment by ganrad** [comment]
This problem is now resolved. AKS clusters 1.18.8+ use 'Containerd' as the container runtime.  With Containerd, it's not possible to leverage the docker engine running on the host to build containers.  The updated solution runs dind in a sidecar container within the devops agent pod and performs the container build.

**Comment by ganrad** [comment]
Closing this issue.  Refer to the comments above.
